FROM python:3.14.0-alpine

ENV DEVPISERVER_SERVERDIR=/devpi/server
RUN mkdir -p $DEVPISERVER_SERVERDIR && \
    mkdir /entrypoint.d

COPY requirements.txt /requirements.txt
RUN apk add --no-cache \
        gcc \
        musl-dev \
        libffi \
        libffi-dev \
    && \
    pip install --no-cache-dir -r /requirements.txt \
    && \
    apk del \
        gcc \
        musl-dev \
        libffi-dev

COPY entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "" ]

EXPOSE 3141
